name: Deploy Crawler

on:
  push:
    branches:
      - feature/fly-deploys
    paths:
      - 'crawler/**'

jobs:
  deploy:
    name: Deploy Crawler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: cd crawler && pnpm install # Use npm if pnpm isnâ€™t pre-installed
      - name: Build
        run: cd crawler && pnpm run build # Runs esbuild to create dist/
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        run: cd crawler && flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_CRAWLER }}